export const siteColors = {
  white: "white",
  grey: "#d3d6dd",
  secondary: "#D3D6DD",
  neon: "#c6f54c",
  deepBlack: "#0a0a11",
  black: "#1c1d24",
  darkGrey: "#46484d",
};

export const menuItems = [
  {name: "laborTimes", label: "Labor Times"},
  {name: "service", label: "Remote Services"},
  {name: "education", label: "Education & Certificates"},
  {name: "marketing", label: "Marketing"},
  {name: "howItWorks", label: "How It Works"},
  {name: "sema", label: "SEMA SHOW 2024"},
];

export const containerSize = "xl";

export const states = [
  {label: "Alabama", value: "Alabama"},
  {label: "Alaska", value: "Alaska"},
  {label: "Arizona", value: "Arizona"},
  {label: "Arkansas", value: "Arkansas"},
  {label: "California", value: "California"},
  {label: "Colorado", value: "Colorado"},
  {label: "Connecticut", value: "Connecticut"},
  {label: "Delaware", value: "Delaware"},
  {label: "Florida", value: "Florida"},
  {label: "Georgia", value: "Georgia"},
  {label: "Hawaii", value: "Hawaii"},
  {label: "Idaho", value: "Idaho"},
  {label: "Illinois", value: "Illinois"},
  {label: "Indiana", value: "Indiana"},
  {label: "Iowa", value: "Iowa"},
  {label: "Kansas", value: "Kansas"},
  {label: "Kentucky", value: "Kentucky"},
  {label: "Louisiana", value: "Louisiana"},
  {label: "Maine", value: "Maine"},
  {label: "Maryland", value: "Maryland"},
  {label: "Massachusetts", value: "Massachusetts"},
  {label: "Michigan", value: "Michigan"},
  {label: "Minnesota", value: "Minnesota"},
  {label: "Mississippi", value: "Mississippi"},
  {label: "Missouri", value: "Missouri"},
  {label: "Montana", value: "Montana"},
  {label: "Nebraska", value: "Nebraska"},
  {label: "Nevada", value: "Nevada"},
  {label: "New Hampshire", value: "New Hampshire"},
  {label: "New Jersey", value: "New Jersey"},
  {label: "New Mexico", value: "New Mexico"},
  {label: "New York", value: "New York"},
  {label: "North Carolina", value: "North Carolina"},
  {label: "North Dakota", value: "North Dakota"},
  {label: "Ohio", value: "Ohio"},
  {label: "Oklahoma", value: "Oklahoma"},
  {label: "Oregon", value: "Oregon"},
  {label: "Pennsylvania", value: "Pennsylvania"},
  {label: "Rhode Island", value: "Rhode Island"},
  {label: "South Carolina", value: "South Carolina"},
  {label: "South Dakota", value: "South Dakota"},
  {label: "Tennessee", value: "Tennessee"},
  {label: "Texas", value: "Texas"},
  {label: "Utah", value: "Utah"},
  {label: "Vermont", value: "Vermont"},
  {label: "Virginia", value: "Virginia"},
  {label: "Washington", value: "Washington"},
  {label: "West Virginia", value: "West Virginia"},
  {label: "Wisconsin", value: "Wisconsin"},
  {label: "Wyoming", value: "Wyoming"},
];

export const averageRepairs = [
  {label: "Less than 5 requests", value: 5},
  {label: "5–10 requests", value: 10},
  {label: "10–20 requests", value: 20},
  {label: "20-50 requests", value: 50},
  {label: "More than 50 requests", value: 60},
];